#!/bin/bash
# Bedrock Dedicated Server (BDS) — native binary, no Java required.
# Requires common.sh to be sourced first.
#
# NOTE: BDS uses Bedrock Edition protocol only (no Java Edition clients).
#       The primary game port is 19132/udp (Bedrock), not 25565/tcp.
#
# NOTE: BDS manages its own authentication via Xbox Live. online_mode and
#       ops/whitelist options from this add-on map approximately to BDS
#       allow-list and permissions.json, but XUIDs are not resolved
#       automatically — player entries are written by name only.
#
# NOTE: BDS is only officially supported on x86_64 and aarch64 Linux.
#
# NOTE: BDS is native Bedrock, so Geyser/Floodgate (which bridge Bedrock into
#       a Java server) do not apply. It has no Java mod/plugin ecosystem, so
#       ViaVersion, the optimization mods, and Extra Mods are also ignored.

BDS_DIR="${BDS_DIR:-${DATA_DIR}/bds}"

# ---------------------------------------------------------------------------
# Download and extract BDS
# ---------------------------------------------------------------------------
download_bds() {
    mkdir -p "${BDS_DIR}"

    bashio::log.info "Fetching Bedrock Dedicated Server download URL..."
    local arch; arch="$(uname -m)"
    local page_url="https://www.minecraft.net/en-us/download/server/bedrock"
    local page
    page="$(curl -fsSLA 'Mozilla/5.0 (compatible; HASS-addon)' "${page_url}" 2>/dev/null)" || {
        bashio::log.fatal "Could not fetch BDS download page."
        return 1
    }

    local zip_url
    if [[ "${arch}" == "aarch64" || "${arch}" == "arm64" ]]; then
        zip_url="$(echo "${page}" | grep -o 'https://www\.minecraft\.net/bedrockdedicatedserver/bin-linux-arm64/[^"]*\.zip' | head -1)"
        # Fall back to preview builds if no stable arm64 build is listed
        [[ -z "${zip_url}" ]] && \
            zip_url="$(echo "${page}" | grep -o 'https://[^"]*arm64[^"]*\.zip' | head -1)"
    else
        zip_url="$(echo "${page}" | grep -o 'https://www\.minecraft\.net/bedrockdedicatedserver/bin-linux/[^"]*\.zip' | head -1)"
    fi

    if [[ -z "${zip_url}" ]]; then
        bashio::log.fatal "Could not determine BDS download URL from the Minecraft website."
        return 1
    fi

    local bds_ver
    bds_ver="$(echo "${zip_url}" | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*' | head -1)"
    MC_VERSION="${bds_ver:-bedrock}"

    local marker="${BDS_DIR}/.bds_version"
    if [[ -f "${BDS_DIR}/bedrock_server" && "$(cat "${marker}" 2>/dev/null)" == "${bds_ver}" ]]; then
        bashio::log.info "BDS ${bds_ver} already up to date."
        return 0
    fi

    bashio::log.info "Downloading BDS ${bds_ver}..."
    if ! curl -fsSLA 'Mozilla/5.0 (compatible; HASS-addon)' -o "${BDS_DIR}/bds.zip" "${zip_url}"; then
        bashio::log.fatal "Failed to download BDS."
        return 1
    fi

    bashio::log.info "Extracting BDS..."
    unzip -o "${BDS_DIR}/bds.zip" -d "${BDS_DIR}" >/dev/null
    rm -f "${BDS_DIR}/bds.zip"
    chmod +x "${BDS_DIR}/bedrock_server"
    echo "${bds_ver}" > "${marker}"
    bashio::log.info "BDS ${bds_ver} ready."
}

# ---------------------------------------------------------------------------
# Write Bedrock server.properties (different keys from Java edition)
# ---------------------------------------------------------------------------
write_bds_properties() {
    bashio::log.info "Writing Bedrock server.properties..."
    {
        echo "# Generated by the Home Assistant Minecraft Server add-on — do not edit manually."
        echo "server-name=$(opt motd)"
        echo "gamemode=$(opt gamemode)"
        echo "difficulty=$(opt difficulty)"
        echo "allow-cheats=$(opt enable_command_block)"
        echo "max-players=$(opt max_players)"
        echo "online-mode=$(opt online_mode)"
        echo "white-list=$(opt white_list)"
        echo "server-port=19132"
        echo "server-portv6=19133"
        echo "view-distance=$(opt view_distance)"
        echo "tick-distance=$(opt simulation_distance)"
        echo "player-idle-timeout=$(opt player_idle_timeout)"
        echo "max-threads=8"
        echo "level-name=$(opt level_name)"
        echo "level-seed=$(opt level_seed)"
        echo "default-player-permission-level=member"
        echo "texturepack-required=false"
        echo "emit-server-telemetry=false"
    } > "${BDS_DIR}/server.properties"
}

# ---------------------------------------------------------------------------
# Write BDS allow-list (whitelist equivalent)
# ---------------------------------------------------------------------------
write_bds_allowlist() {
    local entries="[]"
    local name
    while IFS= read -r name; do
        [[ -z "${name}" ]] && continue
        entries="$(echo "${entries}" | jq --arg n "${name}" \
            '. += [{"name":$n,"xuid":"","ignoresPlayerLimit":false}]')"
    done < <(jq -r '.whitelist[]?' "${OPTIONS}")
    echo "${entries}" | jq '.' > "${BDS_DIR}/allowlist.json"
}

# ---------------------------------------------------------------------------
# Write BDS permissions (ops equivalent)
# ---------------------------------------------------------------------------
write_bds_permissions() {
    local entries="[]"
    local name
    while IFS= read -r name; do
        [[ -z "${name}" ]] && continue
        entries="$(echo "${entries}" | jq --arg n "${name}" \
            '. += [{"permission":"operator","xuid":""}]')"
    done < <(jq -r '.ops[]?' "${OPTIONS}")
    echo "${entries}" | jq '.' > "${BDS_DIR}/permissions.json"
}

prepare_bds() {
    download_bds

    # World symlink: keep world data in share so it's user-accessible
    local level_name; level_name="$(opt level_name)"
    [[ -z "${level_name}" ]] && level_name="world"
    local world_src="${SERVER_DIR}/${level_name}"
    local world_dst="${BDS_DIR}/worlds/${level_name}"
    mkdir -p "${world_src}" "${BDS_DIR}/worlds"
    if [[ ! -L "${world_dst}" ]]; then
        [[ -d "${world_dst}" ]] && mv "${world_dst}" "${world_src}/"
        ln -sfn "${world_src}" "${world_dst}"
    fi

    write_bds_properties
    write_bds_allowlist
    write_bds_permissions

    # Required by BDS: LD_LIBRARY_PATH
    export LD_LIBRARY_PATH="${BDS_DIR}:${LD_LIBRARY_PATH:-}"

    SERVER_LAUNCH=("${BDS_DIR}/bedrock_server")
    SERVER_WORKDIR="${BDS_DIR}"
}
